services:
  php:
    container_name: sc-php
    restart: on-failure
    build:
      context: ./docker/php
      target: php
      args:
        - GROUP_ID=${DOCKER_GROUP_ID}
        - USER_ID=${DOCKER_USER_ID}
    working_dir: /sconcur
    volumes:
      - ./:/sconcur
    extra_hosts:
      - "host.docker.internal:host-gateway"
    command: [ "php", "/sconcur/docker/php/docker-php-stub.php" ]

  mongodb:
    container_name: sc-mongodb
    image: mongo:8.0.5
    restart: unless-stopped
    command: [ "mongod", "--wiredTigerCacheSizeGB", "5" ]
    environment:
      MONGO_INITDB_ROOT_USERNAME: ${MONGO_ADMIN_USERNAME}
      MONGO_INITDB_ROOT_PASSWORD: ${MONGO_ADMIN_PASSWORD}
      MONGO_ADMIN_USERNAME: ${MONGO_ADMIN_USERNAME}
      MONGO_ADMIN_PASSWORD: ${MONGO_ADMIN_PASSWORD}
    ports:
      - ${MONGO_DOCKER_PORT}:${MONGO_PORT}
    volumes:
      - ./docker/mongo/mongo-init.js:/docker-entrypoint-initdb.d/mongo-init.js:ro
      - mongodb:/data/db

volumes:
  mongodb:
    driver: local
